name: Ruby

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sympy
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: |
        sudo apt-get -y install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails yarn:install assets:precompile
    - name: Rubocop
      run: bundle exec rubocop
    - name: Erblint
      run: bundle exec erblint --lint-all
    - name: Setup DB
      run: |-
        cp config/database.yml.github-actions config/database.yml
        bundle exec rails db:setup
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - name: Scan vulnerabilities using Brakeman
      run: bundle exec brakeman
    - name: Test with npm
      run: npm test
    - name: Test with Rake
      run: bundle exec rails test
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    - name: Archive Rails test log
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: Rails test log
        path: log/test.log
